name: Publish

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "Commit SHA"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure env
        run: |
          echo "pkg_build=fastapi_mvc-${{ github.event.inputs.sha }}" >> $GITHUB_ENV
          echo "docs_build=docs-${{ github.event.inputs.sha }}" >> $GITHUB_ENV
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: ${{ env.pkg_build }}
          commit: ${{ github.event.inputs.sha }}
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
      - name: Download docs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: docs.yml
          workflow_conclusion: success
          name: ${{ env.docs_build }}
          commit: ${{ github.event.inputs.sha }}
          path: site
      - name: Publish docs to Netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: site
          production-deploy: true
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}